import turtle
ourScreen = turtle.Screen()
ourTurtle = turtle.Turtle()
ourTurtle.color("red")
ourTurtle.fd(100)
ourTurtle.rt(30)
ourTurtle.fd(100)
ourTurtle.rt(30)
ourScreen.exitonclick()
ourTurtle.reset()
ourTurtle.fd(100)
ourTurtle.rt(90)
ourTurtle.fd(100)
ourTurtle.rt(90)
ourTurtle.lt(90)
ourTurtle.fd(100)
ourTurtle.lt(90)
ourTurtle.
